<div>
    <iframe 
        src="https://widget.coinlib.io/widget?type=horizontal_v2&theme=dark&pref_coin_id=1505&invert_hover=no" 
        width="100%" 
        height="45px" 
        scrolling="auto" 
        marginwidth="0" 
        marginheight="0" 
        frameborder="0" 
        border="0" 
        style="border:0;margin:0;padding:0;display:block;">
    </iframe>
</div>