<?php

return [
    'notifications' => [
        // Profit Notifications
        ['id' => 1, 'type' => 'profit', 'user' => 'Sarah Johnson', 'amount' => 2450, 'instrument' => 'BTC/USD', 'time' => '2 minutes ago', 'avatar' => 'SJ'],
        ['id' => 2, 'type' => 'profit', 'user' => 'Michael Chen', 'amount' => 1890, 'instrument' => 'EUR/USD', 'time' => '5 minutes ago', 'avatar' => 'MC'],
        ['id' => 3, 'type' => 'profit', 'user' => 'David Williams', 'amount' => 3200, 'instrument' => 'Gold', 'time' => '8 minutes ago', 'avatar' => 'DW'],
        ['id' => 4, 'type' => 'profit', 'user' => 'Emma Rodriguez', 'amount' => 975, 'instrument' => 'S&P 500', 'time' => '12 minutes ago', 'avatar' => 'ER'],
        ['id' => 5, 'type' => 'profit', 'user' => 'James Thompson', 'amount' => 1550, 'instrument' => 'Apple', 'time' => '15 minutes ago', 'avatar' => 'JT'],
        ['id' => 6, 'type' => 'profit', 'user' => 'Lisa Wang', 'amount' => 2100, 'instrument' => 'ETH/USD', 'time' => '22 minutes ago', 'avatar' => 'LW'],
        ['id' => 7, 'type' => 'profit', 'user' => 'Robert Martinez', 'amount' => 4125, 'instrument' => 'Nasdaq', 'time' => '28 minutes ago', 'avatar' => 'RM'],
        ['id' => 8, 'type' => 'profit', 'user' => 'Amanda Lee', 'amount' => 3850, 'instrument' => 'Crude Oil', 'time' => '35 minutes ago', 'avatar' => 'AL'],
        ['id' => 9, 'type' => 'profit', 'user' => 'Daniel Kim', 'amount' => 920, 'instrument' => 'EUR/GBP', 'time' => '42 minutes ago', 'avatar' => 'DK'],
        ['id' => 10, 'type' => 'profit', 'user' => 'Maria Garcia', 'amount' => 2875, 'instrument' => 'Silver', 'time' => '48 minutes ago', 'avatar' => 'MG'],
        ['id' => 11, 'type' => 'profit', 'user' => 'Thomas Brown', 'amount' => 3100, 'instrument' => 'Tesla', 'time' => '55 minutes ago', 'avatar' => 'TB'],
        ['id' => 12, 'type' => 'profit', 'user' => 'Natalie Davis', 'amount' => 1675, 'instrument' => 'Amazon', 'time' => '1 hour ago', 'avatar' => 'ND'],
        ['id' => 13, 'type' => 'profit', 'user' => 'Kevin Wilson', 'amount' => 2290, 'instrument' => 'Microsoft', 'time' => '1 hour ago', 'avatar' => 'KW'],
        ['id' => 14, 'type' => 'profit', 'user' => 'Rachel Green', 'amount' => 1450, 'instrument' => 'Google', 'time' => '1 hour ago', 'avatar' => 'RG'],
        ['id' => 15, 'type' => 'profit', 'user' => 'Brian Taylor', 'amount' => 3580, 'instrument' => 'Netflix', 'time' => '1 hour ago', 'avatar' => 'BT'],
        ['id' => 16, 'type' => 'profit', 'user' => 'Jessica White', 'amount' => 810, 'instrument' => 'Meta', 'time' => '2 hours ago', 'avatar' => 'JW'],
        ['id' => 17, 'type' => 'profit', 'user' => 'Andrew Clark', 'amount' => 2740, 'instrument' => 'NVIDIA', 'time' => '2 hours ago', 'avatar' => 'AC'],
        ['id' => 18, 'type' => 'profit', 'user' => 'Olivia Martinez', 'amount' => 1935, 'instrument' => 'AMD', 'time' => '2 hours ago', 'avatar' => 'OM'],
        ['id' => 19, 'type' => 'profit', 'user' => 'William Johnson', 'amount' => 4560, 'instrument' => 'Bitcoin', 'time' => '2 hours ago', 'avatar' => 'WJ'],
        ['id' => 20, 'type' => 'profit', 'user' => 'Sophia Lee', 'amount' => 1260, 'instrument' => 'Ethereum', 'time' => '3 hours ago', 'avatar' => 'SL'],
        
        // Real Estate Investment Notifications
        ['id' => 21, 'type' => 'real_estate', 'user' => 'Michael Brown', 'property' => 'Miami Beachfront Villa', 'amount' => 25000, 'time' => '10 minutes ago', 'avatar' => 'MB'],
        ['id' => 22, 'type' => 'real_estate', 'user' => 'Jennifer Wilson', 'property' => 'New York Downtown Tower', 'amount' => 50000, 'time' => '25 minutes ago', 'avatar' => 'JW'],
        ['id' => 23, 'type' => 'real_estate', 'user' => 'Christopher Lee', 'property' => 'London Historic Estate', 'amount' => 40000, 'time' => '40 minutes ago', 'avatar' => 'CL'],
        ['id' => 24, 'type' => 'real_estate', 'user' => 'Ashley Davis', 'property' => 'Tokyo Smart Tower', 'amount' => 35000, 'time' => '52 minutes ago', 'avatar' => 'AD'],
        ['id' => 25, 'type' => 'real_estate', 'user' => 'Matthew Harris', 'property' => 'Dubai Marina Residence', 'amount' => 20000, 'time' => '1 hour ago', 'avatar' => 'MH'],
        ['id' => 26, 'type' => 'real_estate', 'user' => 'Amanda Taylor', 'property' => 'Singapore Financial Hub', 'amount' => 100000, 'time' => '1 hour ago', 'avatar' => 'AT'],
        ['id' => 27, 'type' => 'real_estate', 'user' => 'Joshua Martin', 'property' => 'Paris Luxury Apartment', 'amount' => 30000, 'time' => '1 hour ago', 'avatar' => 'JM'],
        ['id' => 28, 'type' => 'real_estate', 'user' => 'Megan Robinson', 'property' => 'Sydney Waterfront Estate', 'amount' => 45000, 'time' => '2 hours ago', 'avatar' => 'MR'],
        ['id' => 29, 'type' => 'real_estate', 'user' => 'Ryan White', 'property' => 'Berlin Tech Campus', 'amount' => 75000, 'time' => '2 hours ago', 'avatar' => 'RW'],
        ['id' => 30, 'type' => 'real_estate', 'user' => 'Lauren Hall', 'property' => 'Miami Beachfront Villa', 'amount' => 50000, 'time' => '2 hours ago', 'avatar' => 'LH'],
        ['id' => 31, 'type' => 'real_estate', 'user' => 'Tyler Adams', 'property' => 'London Historic Estate', 'amount' => 60000, 'time' => '3 hours ago', 'avatar' => 'TA'],
        ['id' => 32, 'type' => 'real_estate', 'user' => 'Brittany Nelson', 'property' => 'New York Downtown Tower', 'amount' => 75000, 'time' => '3 hours ago', 'avatar' => 'BN'],
        ['id' => 33, 'type' => 'real_estate', 'user' => 'Eric Peterson', 'property' => 'Tokyo Smart Tower', 'amount' => 70000, 'time' => '3 hours ago', 'avatar' => 'EP'],
        ['id' => 34, 'type' => 'real_estate', 'user' => 'Stephanie Carter', 'property' => 'Dubai Marina Residence', 'amount' => 40000, 'time' => '4 hours ago', 'avatar' => 'SC'],
        
        // Additional Profit Notifications
        ['id' => 35, 'type' => 'profit', 'user' => 'Jonathan Baker', 'amount' => 1670, 'instrument' => 'USD/JPY', 'time' => '4 hours ago', 'avatar' => 'JB'],
        ['id' => 36, 'type' => 'profit', 'user' => 'Samantha Reed', 'amount' => 2345, 'instrument' => 'GBP/USD', 'time' => '4 hours ago', 'avatar' => 'SR'],
        ['id' => 37, 'type' => 'profit', 'user' => 'Gregory Ross', 'amount' => 890, 'instrument' => 'AUD/USD', 'time' => '5 hours ago', 'avatar' => 'GR'],
        ['id' => 38, 'type' => 'profit', 'user' => 'Katherine Foster', 'amount' => 3450, 'instrument' => 'Gold', 'time' => '5 hours ago', 'avatar' => 'KF'],
        ['id' => 39, 'type' => 'profit', 'user' => 'Dennis Cooper', 'amount' => 1765, 'instrument' => 'Silver', 'time' => '5 hours ago', 'avatar' => 'DC'],
        ['id' => 40, 'type' => 'profit', 'user' => 'Rebecca Howard', 'amount' => 2890, 'instrument' => 'Bitcoin', 'time' => '6 hours ago', 'avatar' => 'RH'],
        ['id' => 41, 'type' => 'profit', 'user' => 'Frank Mitchell', 'amount' => 1150, 'instrument' => 'Ethereum', 'time' => '6 hours ago', 'avatar' => 'FM'],
        ['id' => 42, 'type' => 'profit', 'user' => 'Christina Ward', 'amount' => 3200, 'instrument' => 'Solana', 'time' => '6 hours ago', 'avatar' => 'CW'],
        ['id' => 43, 'type' => 'profit', 'user' => 'Russell Cox', 'amount' => 950, 'instrument' => 'Dogecoin', 'time' => '7 hours ago', 'avatar' => 'RC'],
        ['id' => 44, 'type' => 'profit', 'user' => 'Jacqueline Bailey', 'amount' => 2675, 'instrument' => 'Cardano', 'time' => '7 hours ago', 'avatar' => 'JB'],
        ['id' => 45, 'type' => 'profit', 'user' => 'Eugene Rivera', 'amount' => 1430, 'instrument' => 'Polkadot', 'time' => '7 hours ago', 'avatar' => 'ER'],
        ['id' => 46, 'type' => 'profit', 'user' => 'Catherine Simmons', 'amount' => 1980, 'instrument' => 'Litecoin', 'time' => '8 hours ago', 'avatar' => 'CS'],
        ['id' => 47, 'type' => 'profit', 'user' => 'Bruce Patterson', 'amount' => 4320, 'instrument' => 'Chainlink', 'time' => '8 hours ago', 'avatar' => 'BP'],
        ['id' => 48, 'type' => 'profit', 'user' => 'Virginia Gray', 'amount' => 755, 'instrument' => 'Uniswap', 'time' => '8 hours ago', 'avatar' => 'VG'],
        ['id' => 49, 'type' => 'profit', 'user' => 'Ralph Richardson', 'amount' => 2560, 'instrument' => 'Avalanche', 'time' => '9 hours ago', 'avatar' => 'RR'],
        ['id' => 50, 'type' => 'profit', 'user' => 'Rose Cooper', 'amount' => 1740, 'instrument' => 'Polygon', 'time' => '9 hours ago', 'avatar' => 'RC'],
        
        // More Real Estate Notifications
        ['id' => 51, 'type' => 'real_estate', 'user' => 'Samuel Bryant', 'property' => 'Paris Luxury Apartment', 'amount' => 45000, 'time' => '5 hours ago', 'avatar' => 'SB'],
        ['id' => 52, 'type' => 'real_estate', 'user' => 'Martha Jenkins', 'property' => 'Sydney Waterfront Estate', 'amount' => 90000, 'time' => '6 hours ago', 'avatar' => 'MJ'],
        ['id' => 53, 'type' => 'real_estate', 'user' => 'Albert Perry', 'property' => 'Berlin Tech Campus', 'amount' => 150000, 'time' => '7 hours ago', 'avatar' => 'AP'],
        ['id' => 54, 'type' => 'real_estate', 'user' => 'Sandra Hughes', 'property' => 'Miami Beachfront Villa', 'amount' => 100000, 'time' => '8 hours ago', 'avatar' => 'SH'],
        ['id' => 55, 'type' => 'real_estate', 'user' => 'Harry Price', 'property' => 'London Historic Estate', 'amount' => 120000, 'time' => '9 hours ago', 'avatar' => 'HP'],
        ['id' => 56, 'type' => 'real_estate', 'user' => 'Teresa Bailey', 'property' => 'Tokyo Smart Tower', 'amount' => 70000, 'time' => '10 hours ago', 'avatar' => 'TB'],
        ['id' => 57, 'type' => 'real_estate', 'user' => 'Billy Sanders', 'property' => 'Dubai Marina Residence', 'amount' => 60000, 'time' => '11 hours ago', 'avatar' => 'BS'],
        
        // Final Profit Notifications
        ['id' => 58, 'type' => 'profit', 'user' => 'Anne Watson', 'amount' => 1120, 'instrument' => 'S&P 500', 'time' => '10 hours ago', 'avatar' => 'AW'],
        ['id' => 59, 'type' => 'profit', 'user' => 'Joe Brooks', 'amount' => 3340, 'instrument' => 'Nasdaq', 'time' => '11 hours ago', 'avatar' => 'JB'],
        ['id' => 60, 'type' => 'profit', 'user' => 'Donna Bennett', 'amount' => 2875, 'instrument' => 'Dow Jones', 'time' => '12 hours ago', 'avatar' => 'DB'],
        ['id' => 61, 'type' => 'profit', 'user' => 'Wayne Foster', 'amount' => 950, 'instrument' => 'FTSE 100', 'time' => '12 hours ago', 'avatar' => 'WF'],
        ['id' => 62, 'type' => 'profit', 'user' => 'Mildred Kelly', 'amount' => 1670, 'instrument' => 'DAX', 'time' => '13 hours ago', 'avatar' => 'MK'],
        ['id' => 63, 'type' => 'profit', 'user' => 'Steve Russell', 'amount' => 2290, 'instrument' => 'CAC 40', 'time' => '13 hours ago', 'avatar' => 'SR'],
        ['id' => 64, 'type' => 'profit', 'user' => 'Jane Hayes', 'amount' => 3450, 'instrument' => 'Nikkei 225', 'time' => '14 hours ago', 'avatar' => 'JH'],
        ['id' => 65, 'type' => 'profit', 'user' => 'Sean Sullivan', 'amount' => 1830, 'instrument' => 'HSI', 'time' => '14 hours ago', 'avatar' => 'SS'],
        ['id' => 66, 'type' => 'profit', 'user' => 'Kathryn Shaw', 'amount' => 2760, 'instrument' => 'ASX 200', 'time' => '15 hours ago', 'avatar' => 'KS'],
        ['id' => 67, 'type' => 'profit', 'user' => 'Philip Myers', 'amount' => 1225, 'instrument' => 'Brent Oil', 'time' => '15 hours ago', 'avatar' => 'PM'],
        ['id' => 68, 'type' => 'profit', 'user' => 'Janet Ford', 'amount' => 3560, 'instrument' => 'Natural Gas', 'time' => '16 hours ago', 'avatar' => 'JF'],
        ['id' => 69, 'type' => 'profit', 'user' => 'Craig Hamilton', 'amount' => 890, 'instrument' => 'Coffee', 'time' => '16 hours ago', 'avatar' => 'CH'],
        ['id' => 70, 'type' => 'profit', 'user' => 'Ruth Gibson', 'amount' => 2340, 'instrument' => 'Wheat', 'time' => '17 hours ago', 'avatar' => 'RG'],
        ['id' => 71, 'type' => 'profit', 'user' => 'Peter Grant', 'amount' => 1675, 'instrument' => 'Corn', 'time' => '17 hours ago', 'avatar' => 'PG'],
        ['id' => 72, 'type' => 'profit', 'user' => 'Norma Turner', 'amount' => 2890, 'instrument' => 'Sugar', 'time' => '18 hours ago', 'avatar' => 'NT'],
        ['id' => 73, 'type' => 'profit', 'user' => 'Glenn Murray', 'amount' => 1450, 'instrument' => 'Cotton', 'time' => '18 hours ago', 'avatar' => 'GM'],
        ['id' => 74, 'type' => 'profit', 'user' => 'Lillian Reed', 'amount' => 3780, 'instrument' => 'Platinum', 'time' => '19 hours ago', 'avatar' => 'LR'],
        ['id' => 75, 'type' => 'profit', 'user' => 'Paul Carter', 'amount' => 1125, 'instrument' => 'Palladium', 'time' => '19 hours ago', 'avatar' => 'PC'],
        ['id' => 76, 'type' => 'profit', 'user' => 'Diana Ward', 'amount' => 2560, 'instrument' => 'Copper', 'time' => '20 hours ago', 'avatar' => 'DW'],
        ['id' => 77, 'type' => 'profit', 'user' => 'Howard Young', 'amount' => 1980, 'instrument' => 'Aluminum', 'time' => '20 hours ago', 'avatar' => 'HY'],
        ['id' => 78, 'type' => 'profit', 'user' => 'Irene Howell', 'amount' => 3210, 'instrument' => 'Zinc', 'time' => '21 hours ago', 'avatar' => 'IH'],
        ['id' => 79, 'type' => 'profit', 'user' => 'Raymond Bishop', 'amount' => 1730, 'instrument' => 'Nickel', 'time' => '21 hours ago', 'avatar' => 'RB'],
        ['id' => 80, 'type' => 'profit', 'user' => 'Juanita Kim', 'amount' => 4050, 'instrument' => 'Lead', 'time' => '22 hours ago', 'avatar' => 'JK'],
        ['id' => 81, 'type' => 'profit', 'user' => 'Tom Watson', 'amount' => 1340, 'instrument' => 'Tin', 'time' => '22 hours ago', 'avatar' => 'TW'],
        ['id' => 82, 'type' => 'profit', 'user' => 'Stacy Wagner', 'amount' => 2870, 'instrument' => 'Crypto Index', 'time' => '23 hours ago', 'avatar' => 'SW'],
        ['id' => 83, 'type' => 'profit', 'user' => 'Todd Price', 'amount' => 2155, 'instrument' => 'DeFi Index', 'time' => '23 hours ago', 'avatar' => 'TP'],
        ['id' => 84, 'type' => 'profit', 'user' => 'Audrey Russell', 'amount' => 1790, 'instrument' => 'Metaverse Index', 'time' => '1 day ago', 'avatar' => 'AR'],
        
        // Final Real Estate Notifications
        ['id' => 85, 'type' => 'real_estate', 'user' => 'Cindy Ross', 'property' => 'Singapore Financial Hub', 'amount' => 200000, 'time' => '12 hours ago', 'avatar' => 'CR'],
        ['id' => 86, 'type' => 'real_estate', 'user' => 'Lawrence Ortiz', 'property' => 'Berlin Tech Campus', 'amount' => 100000, 'time' => '13 hours ago', 'avatar' => 'LO'],
        ['id' => 87, 'type' => 'real_estate', 'user' => 'Julia Bell', 'property' => 'Miami Beachfront Villa', 'amount' => 75000, 'time' => '14 hours ago', 'avatar' => 'JB'],
        ['id' => 88, 'type' => 'real_estate', 'user' => 'Benjamin Phillips', 'property' => 'New York Downtown Tower', 'amount' => 125000, 'time' => '15 hours ago', 'avatar' => 'BP'],
        ['id' => 89, 'type' => 'real_estate', 'user' => 'Charlotte Adams', 'property' => 'London Historic Estate', 'amount' => 80000, 'time' => '16 hours ago', 'avatar' => 'CA'],
        ['id' => 90, 'type' => 'real_estate', 'user' => 'Daniel Evans', 'property' => 'Tokyo Smart Tower', 'amount' => 105000, 'time' => '17 hours ago', 'avatar' => 'DE'],
        ['id' => 91, 'type' => 'real_estate', 'user' => 'Emily Cooper', 'property' => 'Dubai Marina Residence', 'amount' => 50000, 'time' => '18 hours ago', 'avatar' => 'EC'],
        ['id' => 92, 'type' => 'real_estate', 'user' => 'Frank Harris', 'property' => 'Paris Luxury Apartment', 'amount' => 60000, 'time' => '19 hours ago', 'avatar' => 'FH'],
        ['id' => 93, 'type' => 'real_estate', 'user' => 'Grace Evans', 'property' => 'Sydney Waterfront Estate', 'amount' => 110000, 'time' => '20 hours ago', 'avatar' => 'GE'],
        ['id' => 94, 'type' => 'real_estate', 'user' => 'Henry Walker', 'property' => 'Berlin Tech Campus', 'amount' => 85000, 'time' => '21 hours ago', 'avatar' => 'HW'],
        
        // More Profit Notifications to reach 100
        ['id' => 95, 'type' => 'profit', 'user' => 'Larry Mitchell', 'amount' => 2940, 'instrument' => 'Bitcoin', 'time' => '1 day ago', 'avatar' => 'LM'],
        ['id' => 96, 'type' => 'profit', 'user' => 'Doris Perez', 'amount' => 1680, 'instrument' => 'Ethereum', 'time' => '1 day ago', 'avatar' => 'DP'],
        ['id' => 97, 'type' => 'profit', 'user' => 'Roy Campbell', 'amount' => 2345, 'instrument' => 'Solana', 'time' => '1 day ago', 'avatar' => 'RC'],
        ['id' => 98, 'type' => 'profit', 'user' => 'Lois Stewart', 'amount' => 1875, 'instrument' => 'Cardano', 'time' => '1 day ago', 'avatar' => 'LS'],
        ['id' => 99, 'type' => 'profit', 'user' => 'Ricky Johnson', 'amount' => 3560, 'instrument' => 'Ripple', 'time' => '1 day ago', 'avatar' => 'RJ'],
        ['id' => 100, 'type' => 'profit', 'user' => 'Carla Rodriguez', 'amount' => 1420, 'instrument' => 'Litecoin', 'time' => '1 day ago', 'avatar' => 'CR'],
    ],
];
?>